---

- name: Install ntp package
  yum: name={{ item }} state=present
  with_items:
   - "ntpdate"

- name: Set the correct timezone.
  file:
    src: "/usr/share/zoneinfo/{{ ntp_timezone }}"
    dest: /etc/localtime
    state: link
    force: yes

- name: Force a clock update using ntp
  shell: /usr/sbin/ntpdate {{ ntp_server }}

- name: Install crontab package
  yum: name={{ item }} state=present
  with_items:
   - "crontabs"

- name: Create /etc/cron.d
  file: path={{ item }}
        state=directory
        mode=644
  with_items:
    - '/etc/cron.d'

- name: Set /etc/cron.d/ntpdate
  template: src='cron_ntpdate.erb'
            dest='/etc/cron.d/ntpdate'
            mode=644
            owner=root
            group=root

- name: Enabled the crond service
  service: name=crond state=started enabled=true